# Generated by Django 2.2.4 on 2019-08-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='flightseats.Seat'),
        ),
    ]
