# Generated by Django 2.2.4 on 2019-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightseats', '0002_auto_20190820_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.CharField(max_length=256)),
                ('y_pos', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_point', models.CharField(max_length=256)),
            ],
        ),
    ]
